[network]
name = "devnet"

[accounts.deployer]
mnemonic = "fetch then table grain basic property age ridge arctic parallel vanilla drastic"
balance = 100000000000000

[accounts.wallet_1]
mnemonic = "rely movie provide fly area renew tooth high zero allow distance use"
balance = 100000000000000

[accounts.wallet_2]
mnemonic = "reason size amazing city scale flat direct cloud promote correct mountain degree"
balance = 100000000000000
